#!/bin/bash

argv=("$@")
argc=$#

if [ $argc == 0 ]; then
    echo "Calls ifdown then ifup on the passed ifs"
    echo "Usage: ifreset if1 [if2] [if3] ..."
    exit
fi

for ((i=0;i<$argc;i++)); do
	echo "Resetting: ${argv[$i]}"
	echo `/sbin/ifdown ${argv[$i]}`
	echo 
	echo `/sbin/ifup ${argv[$i]}`
done


