#!/bin/bash

### BEGIN INIT INFO
# Provides:          ip-nat
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts and stops ip-nat services.
# Description:       Starts and stops ip-nat services, installs the iptable rules for NAT services. 
### END INIT INFO

. /lib/lsb/init-functions

start_rules() {
	# The interface to listen to
	IFIN=eth0
	# The interface to forward out to
	IFOUT=wlan0
	
	# Get the subnet for the in interface then prep it for the rules
	SUBADDR=`iftest ${IFIN}`
	SUBADDR=${SUBADDR}0/24
	echo $SUBADDR

	# make sure port forwarding is on
	/bin/echo "1" > /proc/sys/net/ipv4/ip_forward

	#add the rules to the iptables
	iptables -t nat -P POSTROUTING ACCEPT
	iptables -t nat -P PREROUTING ACCEPT
	iptables -A FORWARD -s ${SUBADDR} -d 0/0 -j ACCEPT
	iptables -A FORWARD -m state --state ESTABLISHED,RELATED -d ${SUBADDR} -j ACCEPT
	iptables -t nat -A POSTROUTING -o ${IFOUT} -s ${SUBADDR} -j MASQUERADE

	return 0
}

stop_rules() {
	iptables -F FORWARD
}

case "$1" in
start)
	log_action_begin_msg "Starting NAT services"
	start_rules
	log_action_end_msg $?
	;;

stop)
	log_action_begin_msg "Stopping NAT services"
	stop_rules
	log_action_end_msg $?
	;;

reload)
	log_action_begin_msg "Restarting NAT services"
	stop_rules
	start_rules
	log_action_end_msg $?
	;;

force-reload|restart)
	log_action_begin_msg "Restarting NAT services"
	stop_rules
	start_rules
	log_action_end_msg $?
	;;

*)
	echo "Usage: /etc/init.d/networking {start|stop|reload|restart|force-reload}"
	exit 1
	;;
esac

